In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('C:\\Users\\SRINIVASA SESHADRI K\\OneDrive\\Documents\\MainFlow Services and Technologies Internship\\Task 6 (Project)\\Python Dataset\\archive (3)\\diabetes_data.csv')

In [4]:
type(data)

pandas.core.frame.DataFrame

In [5]:
data.shape

(1879, 46)

In [6]:
data.head(5)

,PatientID,Age,Gender,Ethnicity,SocioeconomicStatus,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,...,TinglingHandsFeet,QualityOfLifeScore,HeavyMetalsExposure,OccupationalExposureChemicals,WaterQuality,MedicalCheckupsFrequency,MedicationAdherence,HealthLiteracy,Diagnosis,DoctorInCharge
0,6000,44,0,1,2,1,32.985284,1,4.499365,2.443385,...,1,73.765109,0,0,0,1.782724,4.486980,7.211349,1,Confidential
1,6001,51,1,0,1,2,39.916764,0,1.578919,8.301264,...,0,91.445753,0,0,1,3.381070,5.961705,5.024612,1,Confidential
2,6002,89,1,0,1,3,19.782251,0,1.177301,6.103395,...,0,54.485744,0,0,0,2.701019,8.950821,7.034944,0,Confidential
3,6003,21,1,1,1,2,32.376881,1,1.714621,8.645465,...,0,77.866758,0,0,1,1.409056,3.124769,4.717774,0,Confidential
4,6004,27,1,0,1,3,16.808600,0,15.462549,4.629383,...,0,37.731808,0,0,0,1.218452,6.977741,7.887940,0,Confidential

In [7]:
data.tail(5)

,PatientID,Age,Gender,Ethnicity,SocioeconomicStatus,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,...,TinglingHandsFeet,QualityOfLifeScore,HeavyMetalsExposure,OccupationalExposureChemicals,WaterQuality,MedicalCheckupsFrequency,MedicationAdherence,HealthLiteracy,Diagnosis,DoctorInCharge
1874,7874,37,0,0,2,2,20.811137,0,10.946207,3.217636,...,1,88.122729,0,0,1,3.154225,3.849584,8.805087,0,Confidential
1875,7875,80,1,0,2,2,27.694312,0,16.067905,7.107335,...,0,77.128599,0,0,1,0.424893,5.217465,0.915878,1,Confidential
1876,7876,38,1,0,0,2,35.640824,0,4.865124,9.881212,...,0,13.148221,0,0,0,0.553757,3.377744,3.017481,1,Confidential
1877,7877,43,0,1,2,0,32.423016,0,6.362936,4.750079,...,0,54.370980,0,0,0,1.132470,0.009250,4.914556,1,Confidential
1878,7878,85,1,0,2,2,33.145119,0,13.854861,5.434137,...,1,43.720860,0,0,1,3.070583,8.483128,7.790921,1,Confidential

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1879 entries, 0 to 1878
Data columns (total 46 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   PatientID                      1879 non-null   int64
 1   Age                            1879 non-null   int64
 2   Gender                         1879 non-null   int64
 3   Ethnicity                      1879 non-null   int64
 4   SocioeconomicStatus            1879 non-null   int64
 5   EducationLevel                 1879 non-null   int64
 6   BMI                            1879 non-null   float64
 7   Smoking                        1879 non-null   int64
 8   AlcoholConsumption             1879 non-null   float64
 9   PhysicalActivity               1879 non-null   float64
 10  DietQuality                    1879 non-null   float64
 11  SleepQuality                   1879 non-null   float64
 12  FamilyHistoryDiabetes          1879 non-null   int64
 13  GestationalDiabetes            1879 non-null   int64
 14  PolycysticOvarySyndrome        1879 non-null   int64
 15  PreviousPreDiabetes            1879 non-null   int64
 16  Hypertension                   1879 non-null   int64
 17  SystolicBP                     1879 non-null   int64
 18  DiastolicBP                    1879 non-null   int64
 19  FastingBloodSugar              1879 non-null   float64
 20  HbA1c                          1879 non-null   float64
 21  SerumCreatinine                1879 non-null   float64
 22  BUNLevels                      1879 non-null   float64
 23  CholesterolTotal               1879 non-null   float64
 24  CholesterolLDL                 1879 non-null   float64
 25  CholesterolHDL                 1879 non-null   float64
 26  CholesterolTriglycerides       1879 non-null   float64
 27  AntihypertensiveMedications    1879 non-null   int64
 28  Statins                        1879 non-null   int64
 29  AntidiabeticMedications        1879 non-null   int64
 30  FrequentUrination              1879 non-null   int64
 31  ExcessiveThirst                1879 non-null   int64
 32  UnexplainedWeightLoss          1879 non-null   int64
 33  FatigueLevels                  1879 non-null   float64
 34  BlurredVision                  1879 non-null   int64
 35  SlowHealingSores               1879 non-null   int64
 36  TinglingHandsFeet              1879 non-null   int64
 37  QualityOfLifeScore             1879 non-null   float64
 38  HeavyMetalsExposure            1879 non-null   int64
 39  OccupationalExposureChemicals  1879 non-null   int64
 40  WaterQuality                   1879 non-null   int64
 41  MedicalCheckupsFrequency       1879 non-null   float64
 42  MedicationAdherence            1879 non-null   float64
 43  HealthLiteracy                 1879 non-null   float64
 44  Diagnosis                      1879 non-null   int64
 45  DoctorInCharge                 1879 non-null   object
dtypes: float64(18), int64(27), object(1)
memory usage: 675.4+ KB

In [9]:
data.describe()

,PatientID,Age,Gender,Ethnicity,SocioeconomicStatus,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,...,SlowHealingSores,TinglingHandsFeet,QualityOfLifeScore,HeavyMetalsExposure,OccupationalExposureChemicals,WaterQuality,MedicalCheckupsFrequency,MedicationAdherence,HealthLiteracy,Diagnosis
count,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,...,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000
mean,6939.000000,55.043108,0.487493,0.755721,0.992017,1.699308,27.687601,0.281533,10.096587,5.200790,...,0.102714,0.111229,48.508643,0.052155,0.103246,0.200639,1.997101,4.957539,5.011736,0.400213
std,542.564896,20.515839,0.499977,1.047558,0.764940,0.885665,7.190975,0.449866,5.914216,2.857012,...,0.303666,0.314500,28.758488,0.222400,0.304361,0.400585,1.122632,2.910934,2.920908,0.490072
min,6000.000000,20.000000,0.000000,0.000000,0.000000,0.000000,15.025898,0.000000,0.000928,0.004089,...,0.000000,0.000000,0.002390,0.000000,0.000000,0.000000,0.004013,0.005384,0.000362,0.000000
25%,6469.500000,38.000000,0.000000,0.000000,0.000000,1.000000,21.469981,0.000000,4.789725,2.751022,...,0.000000,0.000000,23.974098,0.000000,0.000000,0.000000,1.057801,2.420024,2.410113,0.000000
50%,6939.000000,55.000000,0.000000,0.000000,1.000000,2.000000,27.722988,0.000000,10.173865,5.249002,...,0.000000,0.000000,47.519693,0.000000,0.000000,0.000000,1.987170,4.843886,5.035208,0.000000
75%,7408.500000,73.000000,1.000000,1.000000,2.000000,2.000000,33.856460,1.000000,15.285359,7.671402,...,0.000000,0.000000,72.883179,0.000000,0.000000,0.000000,2.946019,7.513933,7.586865,1.000000
max,7878.000000,90.000000,1.000000,3.000000,2.000000,3.000000,39.998811,1.000000,19.996231,9.993893,...,1.000000,1.000000,99.788530,1.000000,1.000000,1.000000,3.999715,9.997165,9.993029,1.000000

In [10]:
data = data.drop_duplicates()
data

,PatientID,Age,Gender,Ethnicity,SocioeconomicStatus,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,...,TinglingHandsFeet,QualityOfLifeScore,HeavyMetalsExposure,OccupationalExposureChemicals,WaterQuality,MedicalCheckupsFrequency,MedicationAdherence,HealthLiteracy,Diagnosis,DoctorInCharge
0,6000,44,0,1,2,1,32.985284,1,4.499365,2.443385,...,1,73.765109,0,0,0,1.782724,4.486980,7.211349,1,Confidential
1,6001,51,1,0,1,2,39.916764,0,1.578919,8.301264,...,0,91.445753,0,0,1,3.381070,5.961705,5.024612,1,Confidential
2,6002,89,1,0,1,3,19.782251,0,1.177301,6.103395,...,0,54.485744,0,0,0,2.701019,8.950821,7.034944,0,Confidential
3,6003,21,1,1,1,2,32.376881,1,1.714621,8.645465,...,0,77.866758,0,0,1,1.409056,3.124769,4.717774,0,Confidential
4,6004,27,1,0,1,3,16.808600,0,15.462549,4.629383,...,0,37.731808,0,0,0,1.218452,6.977741,7.887940,0,Confidential
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1874,7874,37,0,0,2,2,20.811137,0,10.946207,3.217636,...,1,88.122729,0,0,1,3.154225,3.849584,8.805087,0,Confidential
1875,7875,80,1,0,2,2,27.694312,0,16.067905,7.107335,...,0,77.128599,0,0,1,0.424893,5.217465,0.915878,1,Confidential
1876,7876,38,1,0,0,2,35.640824,0,4.865124,9.881212,...,0,13.148221,0,0,0,0.553757,3.377744,3.017481,1,Confidential
1877,7877,43,0,1,2,0,32.423016,0,6.362936,4.750079,...,0,54.370980,0,0,0,1.132470,0.009250,4.914556,1,Confidential
1878,7878,85,1,0,2,2,33.145119,0,13.854861,5.434137,...,1,43.720860,0,0,1,3.070583,8.483128,7.790921,1,Confidential

In [11]:
data.isnull()

,PatientID,Age,Gender,Ethnicity,SocioeconomicStatus,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,...,TinglingHandsFeet,QualityOfLifeScore,HeavyMetalsExposure,OccupationalExposureChemicals,WaterQuality,MedicalCheckupsFrequency,MedicationAdherence,HealthLiteracy,Diagnosis,DoctorInCharge
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1874,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1875,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1876,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1877,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1878,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [12]:
data.isnull().sum()

PatientID                        0
Age                              0
Gender                           0
Ethnicity                        0
SocioeconomicStatus              0
EducationLevel                   0
BMI                              0
Smoking                          0
AlcoholConsumption               0
PhysicalActivity                 0
DietQuality                      0
SleepQuality                     0
FamilyHistoryDiabetes            0
GestationalDiabetes              0
PolycysticOvarySyndrome          0
PreviousPreDiabetes              0
Hypertension                     0
SystolicBP                       0
DiastolicBP                      0
FastingBloodSugar                0
HbA1c                            0
SerumCreatinine                  0
BUNLevels                        0
CholesterolTotal                 0
CholesterolLDL                   0
CholesterolHDL                   0
CholesterolTriglycerides         0
AntihypertensiveMedications      0
Statins                          0
AntidiabeticMedications          0
FrequentUrination                0
ExcessiveThirst                  0
UnexplainedWeightLoss            0
FatigueLevels                    0
BlurredVision                    0
SlowHealingSores                 0
TinglingHandsFeet                0
QualityOfLifeScore               0
HeavyMetalsExposure              0
OccupationalExposureChemicals    0
WaterQuality                     0
MedicalCheckupsFrequency         0
MedicationAdherence              0
HealthLiteracy                   0
Diagnosis                        0
DoctorInCharge                   0
dtype: int64

In [13]:
data.isnull().sum().sum()

0

In [14]:
import numpy as np
from scipy import stats

In [16]:
data.columns #detect outliers using IQR

Index(['PatientID', 'Age', 'Gender', 'Ethnicity', 'SocioeconomicStatus',
       'EducationLevel', 'BMI', 'Smoking', 'AlcoholConsumption',
       'PhysicalActivity', 'DietQuality', 'SleepQuality',
       'FamilyHistoryDiabetes', 'GestationalDiabetes',
       'PolycysticOvarySyndrome', 'PreviousPreDiabetes', 'Hypertension',
       'SystolicBP', 'DiastolicBP', 'FastingBloodSugar', 'HbA1c',
       'SerumCreatinine', 'BUNLevels', 'CholesterolTotal', 'CholesterolLDL',
       'CholesterolHDL', 'CholesterolTriglycerides',
       'AntihypertensiveMedications', 'Statins', 'AntidiabeticMedications',
       'FrequentUrination', 'ExcessiveThirst', 'UnexplainedWeightLoss',
       'FatigueLevels', 'BlurredVision', 'SlowHealingSores',
       'TinglingHandsFeet', 'QualityOfLifeScore', 'HeavyMetalsExposure',
       'OccupationalExposureChemicals', 'WaterQuality',
       'MedicalCheckupsFrequency', 'MedicationAdherence', 'HealthLiteracy',
       'Diagnosis', 'DoctorInCharge'],
      dtype='object')